from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .models import codeHistory
from .import db
import subprocess
import glob

'''Contains views definitions for the website.'''

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    '''
    Defines the homepage functionality.
    
    Returns: the homepage.
    '''
    return render_template('home.html' ,user=current_user)

@views.route('/fix_code')
@login_required
def fix_code():
    '''
    Defines the homepage functionality.
    
    Returns: the homepage.
    '''
    code_id = request.args.get('code_id')
    code = codeHistory.query.get(code_id)
    return render_template('fix_code.html', user=current_user,code=code)


@views.route('/dummy_user')
def dummy_user_home():
    '''
    Defines the homepage functionality for users without an account.
    
    Returns: the homepage.
    '''
    return render_template('fix_code.html', user=None)

@views.route('/save_code', methods=['POST'])
@login_required
def save_code():
    if request.method == 'POST':
        title = request.form.get('code_title')
        content = request.form.get('code_content')
        new_code = codeHistory(title=title, content=content, user_id=current_user.id)
        db.session.add(new_code)
        db.session.commit()
        return redirect(url_for('views.home'))

@views.route('/submit', methods=['POST'])
def submit():
    if request.method == 'POST':
        # Get the text from the form
        c_code = request.form['text']

        # Write the text to a file
        with open('input.c', 'w') as original_file:
            original_file.write(c_code)

        # Invoke the C code as a subprocess, passing the filename as an argument
        c_files = glob.glob("BettyFixerFiles/Betty-Fixer/*.c")
        command = ["gcc"] + c_files + ["-o", "bettyfixer"]
        subprocess.run(command)
        subprocess.run(["./bettyfixer", "input.c"])
        # Read the formatted output from the file generated by the c code
        with open('input.c', 'r') as formatted_file:
            formatted_code = formatted_file.read()
        
        # Render a template with the formatted code
        return render_template('formatted.html', formatted_code=formatted_code, user= current_user)